name: Tinymce PROD Deployment

on:
  release: 
    types: [published]
    
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    name: "Build and deploy"
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch   
#       - name: Build
#         run: |
#           yarn
#           yarn skin-build:prod
#           yarn copy:tinymce
#           yarn build:helpers
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.PROD_GH_ACTIONS_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.PROD_GH_ACTIONS_AWS_SECRET }}
      #     role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
      #     role-duration-seconds: 1200
      #     aws-region: us-east-1
      # - name: Sync files to the s3 bucket
      #   run: |
      #     aws s3 sync dist s3://${{ secrets.PROD_S3_BUCKET }}/v0.0.47 --exclude '*.git' --delete
      #     aws s3 cp dist/tinymce-loader.js s3://${{ secrets.PROD_S3_BUCKET}}/ --metadata-directive REPLACE --cache-control max-age=300
      #     aws s3 cp dist/index.html s3://${{ secrets.PROD_S3_BUCKET }}/ --metadata-directive REPLACE --cache-control max-age=300
